plugins:
  - jekyll-relative-links
#  - jekyll-target-blank

relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-slate

title: "Ursinus WebIDE"
description: "Ursinus WebIDE"

url                      : https://jjmorris2000.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/Ursinus-WebIDE" # the subpath of your site, e.g. "/blog"

formlink: https://docs.google.com/forms/d/e/

publickey: |
    -----BEGIN PUBLIC KEY-----
    -----END PUBLIC KEY-----
canvascourseid: 18818
    
# Reading Files
include:
  - .htaccess
  - _pages
  - files

assets:
  sources:
    - assets
